### ISSUE TITLE
C++20 u8 literals incompatible with char literals

### ISSUE THREAD

**Issue by pezcode** [juliettef/IconFontCppHeaders#15]
C++20 changed the underlying type of u8 literals from char to char8_t, which makes them incompatible. You can't concatenate them, nor can you pass char8_t* to functions expecting char*.

A few ways of mitigating this are discussed [here](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1423r0.html#remediation), one of which being ordinary single byte escape sequences like it's done in the C version of the header files.

I'm not sure if this needs fixing at all, since anyone who requires interoperability with char can switch to the C headers. Just wanted to bring it to your attention.

**Comment by juliettef** [comment]
Thanks for the heads up, I won't do anything yet whilst I think about it.

**Comment by ocornut** [comment]
I believe you could just add a cast in there!

So
```
u8"\uf000"
```
Becomes
```
(const char*)u8"\uf000"
```

What next? Some agressive compiler flags are warnings on C-style cast .... :(
So you may need to hide the cast itself in a macro defined differently depending on whether the code is compiled in C or C++.

**Comment by judicaelclair** [comment]
I found this useful [post](https://stackoverflow.com/questions/57402464/is-c20-char8-t-the-same-as-our-old-char) - cleared quite a few things up for me. Quite disgusting having to use `reinterpret_cast` though...

**Comment by KABoissonneault** [comment]
Note that this is already broken on the latest Visual Studio, with /std:c++latest. I've been using `reinterpret_cast` to avoid modifying the headers.

Can't the "u8" prefix just be removed, given existing users probably all expect `char`? Or at least, can't the tool generate macro variants where the existing version still uses `char` and ex: ICON_FA_AD_U8 would be `char8_t`?

**Comment by ocornut** [comment]
You can use the _c version of the header which contains the exact same values but encoded in a way that has been standardized a million years ago, since c++ cannot be trusted to keep any compatibility with itself.

I would suggest this project to just rename the _c.h header into the existing header, solves everyone problems and be done with it. You might want to append a “// U+XXXX” marker in comment at the end of the line.

**Comment by ocornut** [comment]
Another possibility is that maybe \u now works on regular strings for frankly it seems so more widely compatible to stick to the C version.

**Comment by juliettef** [comment]
Good points, thank you. Following @ocornut 's suggestion, here's what I plan to do. Thoughts?

1. change the generator for *.h files to use the one for *_c.h files with an additional comment per line
e.g. #define ICON_FA_GLASS "\xef\x80\x80"    // U+f000

2. delete the redundant *_c.h files
