### ISSUE TITLE
I use consFontAwesome.h in VS2013 +Imgui 1.50,but compile turn on error

### ISSUE THREAD

**Issue by zhouxs1023** [juliettef/IconFontCppHeaders#2]
I use consFontAwesome.h in VS2013 +Imgui 1.50,but compile turn on C2065 error:u8 undeclared identifier as blow:
step1： add #include "IconsFontAwesome.h" in main function;
step2: 
ImGuiIO& io = ImGui::GetIO();
	io.Fonts->AddFontDefault();
	// merge in icons from Font Awesome
	static const ImWchar icons_ranges[] = { 0xf000, 0xf3ff, 0 };
	ImFontConfig icons_config; 
	icons_config.MergeMode = true; 
	icons_config.PixelSnapH = true;
	io.Fonts->AddFontFromFileTTF("../../extra_fonts/fontawesome-webfont.ttf", 16.0f, &icons_config, icons_ranges);

step3:ImGui::Text( ICON_FA_FILE "  File" ); 

but compile turn on C2065 error:u8 undeclared identifier as blow:
![qq 20160707230812](https://cloud.githubusercontent.com/assets/905931/16658116/b4b17e8e-4497-11e6-8c73-6f846fb12e81.png)

**Comment by dougbinks** [comment]
Visual Studio 2013 doesn't support the new C++11 string literals, so you can either upgrade to a newer version of Visual Studio or use [IconsFontAwesome_c.h](https://github.com/juliettef/IconFontCppHeaders/blob/master/IconsFontAwesome_c.h) which provides a more backwards compatible version.

**Comment by zhouxs1023** [comment]
I use IconsFontAwesome_c.h to build icon font,but crash in imgui_draw.cpp Line 1273 ==>"IM_ASSERT(font_offset >= 0);"
![qq 20160708122803](https://cloud.githubusercontent.com/assets/905931/16677376/b824de42-4507-11e6-9315-9d258cd4ede3.png)

**Comment by dougbinks** [comment]
I'm not sure what's causing that. The code in the example on the readme and your code snippet (with the ImGui::Text called in the demo after the "Hello, world!" text.

I didn't notice before but the font ranges you're using are wrong - you should use:

    static const ImWchar icons_ranges[] = { ICON_MIN_FA, ICON_MAX_FA, 0 };

as per the [readme](https://github.com/juliettef/IconFontCppHeaders/blob/master/README.md). However I don't think that is your problem. Can you post your code somewhere for me to take a look, and which version of ImGui are you using?

**Comment by zhouxs1023** [comment]
I used imgui1.50 wip+vs2013,compile it successfully,but run exe turn on crash in imgui_draw.cpp Line 1273 ==>"IM_ASSERT(font_offset >= 0);"
Later I used imgui1.48+vs2013,but run exe turn on crash in imgui_draw.cpp Line 1248 ==>"IM_ASSERT(font_offset >= 0);"

I added codes steps as blow:
steip 1.add header file;
![qq 20160708201517](https://cloud.githubusercontent.com/assets/905931/16687408/ff6c0486-454a-11e6-9b84-c9fac6ed2bfb.png)
 step2: add icon font code:
![qq 20160708201539](https://cloud.githubusercontent.com/assets/905931/16687425/2378e2e0-454b-11e6-8990-7ab0f61d0826.png)
step3:add text in imgui windows
![qq 20160708201604](https://cloud.githubusercontent.com/assets/905931/16687412/0ace1044-454b-11e6-837c-48aceadae3b6.png)
Additions:
fontawesome-webfont.ttf
![qq 20160708203711](https://cloud.githubusercontent.com/assets/905931/16687534/cc634cb0-454b-11e6-80b3-0dd382330e9c.png)
IconsFontAwesome_c.h
![qq 20160708203726](https://cloud.githubusercontent.com/assets/905931/16687552/eba96b0e-454b-11e6-9a2b-02e97ae6119c.png)

**Comment by dougbinks** [comment]
I'm taking a look at this now - it would be easier with text and not images for the code but the changes are small so should be fairly easy to work out.

**Comment by dougbinks** [comment]
I've done exactly those changes with [ImGui Version 1.50 WIP](https://github.com/ocornut/imgui/commit/5d4cf1c3f35834f05469147fb0aef8174c638334) and VS2015 and don't get the crash.

If you could check if the program crashes without the changes, that would be great. Meanwhile I'll check out an install of Visual Studio 2013 which will take a fair amount of time to do.

**Comment by zhouxs1023** [comment]
May be a 。ttf file error，Redownload.ttf file，compile it sucessfully now,Thanks!

**Comment by dougbinks** [comment]
Great - I did manage to install VS2013 and this did indeed work, but glad you found the problem and solved it!
