### ISSUE TITLE
Duplicate ICON_MD_FLOURESCENT in IconsMaterialDesign.h

### ISSUE THREAD

**Issue by jokteur** [juliettef/IconFontCppHeaders#27]
Hi,
In IconsMaterialDesign.h, there are between lines 827 and 829 duplicated ICON_MD_FLOURESCENT. Compiling with this file gives annoying preprocessor warnings. I think it was introduced in 80b7e5a11f29c60f89444b0030f916850977a710. It compiles fine before this commit.

**Comment by juliettef** [comment]
This error is upstream in the Material Design icons where 'flourescent' (sic) is a duplicate name and 'ec31' is a duplicate codepoint:
- [_flourescent_ **ec31**](https://github.com/google/material-design-icons/blob/f7bd4f25f3764883717c09a1fd867f560c9a9581/font/MaterialIcons-Regular.codepoints#L818)
- [_flourescent_ f00d](https://github.com/google/material-design-icons/blob/f7bd4f25f3764883717c09a1fd867f560c9a9581/font/MaterialIcons-Regular.codepoints#L819)
- [fluorescent **ec31**](https://github.com/google/material-design-icons/blob/f7bd4f25f3764883717c09a1fd867f560c9a9581/font/MaterialIcons-Regular.codepoints#L820)
As a quick workaround I suggest you manually delete 'flourescent ec31' from IconsMaterialDesign.h. 
I'll raise the issue of the duplicated name with them.

**Comment by juliettef** [comment]
@jokteur since the upstream issue isn't fixed yet, I've added for now a workaround that deletes 'flourescent ec31' from the header files. I hope this helps.

**Comment by juliettef** [comment]
The [upstream issue was closed without a fix](https://github.com/google/material-design-icons/issues/1404). The workaround stays and I'm closing this issue.
