### ISSUE TITLE
Add FontAwesome6Pro

### ISSUE THREAD

**Issue by aeris170** [juliettef/IconFontCppHeaders#29]
There exists a working version that is a fork of this repo, I think it should be merged. What do you think?

**Comment by juliettef** [comment]
We currently can't support FontAwesome 6 Pro. [This is why](https://github.com/juliettef/IconFontCppHeaders/issues/21#issuecomment-1047958916 ).
Do feel free to ask FortAwesome again to open source their FA6 Pro `icons.yaml` file.

If you send me a link to the fork you've mentioned, I'll add it to the [readme](https://github.com/juliettef/IconFontCppHeaders#font-awesome-6-pro) together with [@jakerieger's](https://github.com/jakerieger/IconFontCppHeaders).

**Comment by aeris170** [comment]
I'm sorry I didn't know FA had different icons.yml metadata for Free and Pro version. It's a shame they bar metadata behind a licence. The fork I mentioned was [@jakerieger's](https://github.com/jakerieger/IconFontCppHeaders).

(Do you accept PR's? I would like to modify the python script to make it interactive - i.e. select which fonts and for which language to generate the headers etc.)

**Comment by juliettef** [comment]
Yes, it is a shame indeed.

We do accept PRs but only for [things that we consider useful](https://github.com/juliettef/IconFontCppHeaders/pulls?q=is%3Apr+is%3Aclosed). We also try to keep the script as simple as possible.
Thank you for your offer but interactivity would make the script harder to run. If you implement it on your branch I'll link to it for people who are interested.
