### ISSUE TITLE
Use IconsKenney_c.h to merge iconfont,but turn on error

### ISSUE THREAD

**Issue by zhouxs1023** [juliettef/IconFontCppHeaders#3]
VS2013+imgui1.48
step1:add header file
            #include "IconsKenney_c.h"
step2:  merge in icons from IconsKenney 
	          static const ImWchar icons_ranges[] = { ICON_MIN_KI, ICON_MAX_KI, 0 };
          	ImFontConfig icons_config; 
          	icons_config.MergeMode = true; 
         	icons_config.PixelSnapH = true; 
         	icons_config.MergeGlyphCenterV = true;
         	io.Fonts->AddFontFromFileTTF("../../extra_fonts/kenney-icon-font.ttf", 32.0f, &icons_config,     icons_ranges);
step3:add iconfont in imgui windows
         ImGui::Button(ICON_KI_MOVIE, ImVec2(32, 32));
Run later will turn on error as below:
![qq 20160710012724](https://cloud.githubusercontent.com/assets/905931/16709243/80f7c2e0-463d-11e6-8ae5-ff25677b3aab.png)

**Comment by dougbinks** [comment]
This appears to be either an issue with [stb_truetype](https://github.com/nothings/stb) or [dear imgui](https://github.com/ocornut/imgui), I think perhaps the later.

Reducing the size of the font requested, say to 10.0f, works for me.

For brevity and convenience, please just copy the line of the assertion or callstack in text in future - images aren't needed as they tell me very little. Thanks!

**Comment by dougbinks** [comment]
After further research the Kenny Icon Font appears to be a bit broken. I've been able to fix this by opening and saving in [FontForge](http://fontforge.github.io/), though some of the fonts appear to be a bit offset still, however they seem to load fine now.

[Kenney-Icon-Font-Fixed.zip](https://github.com/juliettef/IconFontCppHeaders/files/356026/Kenney-Icon-Font-Fixed.zip)
