### ISSUE TITLE
how to print rotated icon font?

### ISSUE THREAD

**Issue by AlfredXiaSF** [juliettef/IconFontCppHeaders#32]
How can I implement a rotated icon font to indicate task progress when printing?
For example how to rotate spinner in imgui?
```
ImGui::Text(ICON_FA_SPINNER);
```

**Comment by dougbinks** [comment]
I often use [NanoVG when I need complex animation](https://github.com/memononen/nanovg), but this is also possible with [Dear ImGui as per this example](https://github.com/ocornut/imgui/issues/1286#issue-251214314).

**Comment by AlfredXiaSF** [comment]
@dougbinks Think you for your reply! I'll have a try.
