### ISSUE TITLE
Icon not display

### ISSUE THREAD

**Issue by CowNowK** [juliettef/IconFontCppHeaders#37]
![image](https://github.com/juliettef/IconFontCppHeaders/assets/133740174/3f6b6e0b-a023-40b7-9199-ea66c45893ac)

Code:
```cpp
ImGui::Text(ICON_FA_ADDRESS_BOOK 
	ICON_FA_ADDRESS_CARD 
	ICON_FA_ANGRY 
	ICON_FA_ARROW_ALT_CIRCLE_DOWN 
	ICON_FA_ARROW_ALT_CIRCLE_LEFT 
	ICON_FA_ARROW_ALT_CIRCLE_RIGHT 
	ICON_FA_ARROW_ALT_CIRCLE_UP 
	ICON_FA_BACKWARD 
	ICON_FA_BACON 
	ICON_FA_BACTERIA 
	ICON_FA_BACTERIUM 
	ICON_FA_BAHAI 
	ICON_FA_BALANCE_SCALE 
	ICON_FA_BALANCE_SCALE_LEFT 
	ICON_FA_BALANCE_SCALE_RIGHT 
	ICON_FA_BAN 
	ICON_FA_BAND_AID 
	ICON_FA_BARCODE 
	ICON_FA_BARS);
```
Out of thousands of icons, less than 50 can be displayed correctly

**Comment by juliettef** [comment]
Your missing fonts are not free in the `Regular` style. ([example](https://fontawesome.com/v5/search?q=bacterium&o=r&s=regular%2Csolid))  
You need to either switch to the `Solid` style, or buy Font Awesome Pro to get them.
