### ISSUE TITLE
How to produce own icon for ttf file?

### ISSUE THREAD

**Issue by zhouxs1023** [juliettef/IconFontCppHeaders#4]
If the icon that I need  can not find  from the TTF file, I need own icon, how can I put my own icon into the TTF file ?

**Comment by juliettef** [comment]
I've not done this myself but I think you can use [Fontello](http://fontello.com/) or as @dougbinks  [suggested](https://github.com/juliettef/IconFontCppHeaders/issues/3#issuecomment-231587605), use [Fontforge](http://fontforge.github.io/).
You'll then need to add a new define for your icon to the header file.
