### ISSUE TITLE
Change settings of Material Symbol in Dear Imgui

### ISSUE THREAD

**Issue by lesauxvi** [juliettef/IconFontCppHeaders#43]
First of all, thank you for your work and the recent additions. I would like to switch from Material Icons to Material Symbols for an application. I use the font in a GUI application built using Dear Imgui. I embedded the font using `binary_to_compress_c.cpp` file available in Dear Imgui and added it to the using something like :

```
ImFontConfig font_config_1;
    font_config_1.MergeMode = true;
    font_config_1.PixelSnapH = true;
    static constexpr ImWchar ms_icons_ranges[] = { ICON_MIN_MS, ICON_MAX_MS, 0 };
    io.Fonts->AddFontFromMemoryCompressedTTF(material_symbols_sharp_compressed_data,
                                         material_symbols_sharp_compressed_size,
                                         ICON_SIZE, &font_config_1, ms_icons_ranges);
```

It is working perfectly fine. However, I wonder how I can tune the font. For example, I would like to activate the fill option. How and where can I do that?

I looked at the `GenerateIconFontCppHeaders.py` file available in the repository, and found no clue.

Any help will be highly appreciated.

**Comment by juliettef** [comment]
@lesauxvi thank you, glad you found the update useful.

**Comment by lesauxvi** [comment]
Thanks for the feedback. I will have a look at your suggestion and see if it can solve my "issue".

Anyway, many thanks !

**Comment by lesauxvi** [comment]
FYI, the link you have suggested proposes a solution that works perfectly. It relies on the `fonttools` python package. You can easily generate a static font with the desired settings using the command line:

`fonttools.exe varLib.mutator '.\MaterialSymbolsSharp[FILL,GRAD,opsz,wght].ttf' wght=400 FILL=1 GRAD=0 opsz=40`

This will generate a new font, called '.\MaterialSymbolsSharp[FILL,GRAD,opsz,wght]-instance.ttf' with the settings defined above. You just have to embed this new static font in your app and you are good to go.

@dougbinks, many thanks for your help!
