### ISSUE TITLE
MaterialDesignIcons

### ISSUE THREAD

**Issue by madeso** [juliettef/IconFontCppHeaders#7]
Hello,

It would be great if the material design icons would be included as well. From what I can tell they are the google material icons with community extensions and a acceptable license.

Source repo:
https://github.com/Templarian/MaterialDesign

Font & css repo:
https://github.com/Templarian/MaterialDesign-Webfont

Icons list:
https://cdn.materialdesignicons.com/2.4.85/
https://materialdesignicons.com/

**Comment by juliettef** [comment]
Thanks I'll take a look.

**Comment by juliettef** [comment]
Added, thanks for the suggestion.
