### ISSUE TITLE
ForkAwesome FontAwesome confusion

### ISSUE THREAD

**Issue by olilarkin** [juliettef/IconFontCppHeaders#8]
https://github.com/juliettef/IconFontCppHeaders/blob/9cab4b9b82cb1b75a97a0e7e3ea01dd1fbc4c1a9/IconsForkAwesome.h#L6

i think this line should be

```#define FONT_ICON_FILE_NAME_FK "forkawesome-webfont.ttf"```

**Comment by juliettef** [comment]
Thanks for finding and reporting that issue
