### ISSUE TITLE
[C#] Unrecognized escaped sequence with 2 digits code point

### ISSUE THREAD

**Issue by garyng** [juliettef/IconFontCppHeaders#9]
Seems like C# is not happy with 2 digits code point though:
![image](https://user-images.githubusercontent.com/4453664/61870588-0c77e680-af11-11e9-9e12-9eb73b7dec80.png)

Padding with `0`s will make them work:
![image](https://user-images.githubusercontent.com/4453664/61870745-755f5e80-af11-11e9-8cf0-a4aeae877be3.png)

**Comment by juliettef** [comment]
Thanks for pointing this out. Is it being flagged by the syntax highlighting only or does it also break the code?

**Comment by garyng** [comment]
It breaks the code.

**Comment by juliettef** [comment]
Ok thanks I'll fix it asap

**Comment by juliettef** [comment]
Thanks for reporting this issue. Let me know if there are any problems.

**Comment by garyng** [comment]
That was really fast! Thanks!
